#!/bin/bash


function libreoffice {
# 
echo ''
show_question 'Nadaljujem z namestitvijo LibreOffice iz Debian Backports? (D)a, (N)e : ' && read REPLY
echo ''
case $REPLY in
# Potrditev
[Dd]* )
    
#----- Namestitev LIBREOFFICE -----#


echo -e "\ndeb http://http.debian.net/debian $CODENAME-backports main" | tee -a /etc/apt/sources.list 
apt-get -y --force-yes update
apt-get -y --force-yes upgrade
apt-get -t -y --force-yes jessie-backports install libreoffice
show_success 'Končano.'
main
    ;;
# Zavrnitev
[Nn]* )
    clear && main
    ;;
# Napaka
* )
    clear && show_error '\aOprosti, poskusi znova.'
    libreoffice
    ;;
esac
}
